name: '${id}'
description: '${description}'
main: me.lucko.chatformatter.ChatFormatterPlugin
authors: [ 'Luck', 'CG360' ]
depend: [ 'Vault' ]

version: '${plugin_version}'
api-version: '${minecraft_version}'

commands:
  vaultchatformatter:
    description: Reload the configuration
    permission: vaultchatformatter.reload
    usage: "Did you mean to run '/vaultchatformatter reload'?"
